WebFontConfig={google:{families:['Niconne','Norican','Oswald::latin']}};function mainmenu(){$("ul.menu ul").css({display:"none"});$("ul.menu li").hover(function(){$(this).find('ul:first').css({visibility:"visible",display:"none"}).show(200);},function(){$(this).find('ul:first').css({visibility:"hidden"});});}
$(document).ready(function(){var wf=document.createElement('script');wf.src=('https:'==document.location.protocol?'https':'http')+
'://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';wf.type='text/javascript';wf.async='true';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(wf,s);mainmenu();if($('#slider').length){$('#slider').nivoSlider();}
if($("ul.cat-menu").length){var t_container=$("ul.cat-menu"),t_items=t_container.find("li"),t_anchor=t_items.find("a");t_anchor.click(function(){t_items.find('.active').removeClass('active');$(this).find("span.arrow-down").addClass("active");});animatedcollapse.init();animatedcollapse.addDiv('categories','fade=0,speed=400,group=srv,hide=1')
animatedcollapse.addDiv('archives','fade=0,speed=400,group=srv,hide=1')
animatedcollapse.ontoggle=function($,divobj,state){}}
var $container=$('.gallery-container');if($container.length){$($container).find("> div").each(function(){$(this).addClass("column no-margin all-sort");$(this).find(".gallery-image img").after('<span class="image-overlay"> <span class="image-overlay-inside"> </span> </span>');});$container.isotope({filter:'*',animationOptions:{duration:750,easing:'linear',queue:false}});if($("div#sorting-container").length){$("div#sorting-container a").click(function(){$("div#sorting-container a").removeClass("active_sort");var selector=$(this).attr('data-filter');$(this).addClass("active_sort");$container.isotope({filter:selector,animationOptions:{duration:750,easing:'linear',queue:false}});return false;});}}
if($(".testimonial-carousel").length){$('ul.testimonial-carousel').jcarousel({scroll:1});}
if($("#mycarousel").length){$ul=$("#mycarousel ul:first ");$li=$("#mycarousel ul:first li");function mycarousel_initCallback(carousel){$('.jcarousel-control a:first').addClass("active");$($ul).find("li:first").addClass("active");$("a#mycarousel-prev").addClass("disabled");$('.jcarousel-control a').bind('click',function(){$($li).removeClass("active");$($li).eq($(this).index()).addClass("active");$(".jcarousel-control a").removeClass("active");$(this).addClass("active");if($(this).index()==0){$("a#mycarousel-prev").addClass("disabled");}else{$("a#mycarousel-prev").removeClass("disabled");}
if($(this).next("a").length==0){$("a#mycarousel-next").addClass("disabled");}else{$("a#mycarousel-next").removeClass("disabled");}
carousel.scroll($.jcarousel.intval($(this).text()));return false;});$('.jcarousel-scroll select').bind('change',function(){carousel.options.scroll=$.jcarousel.intval(this.options[this.selectedIndex].value);return false;});$('#mycarousel-next').bind('click',function(){$current=$('.jcarousel-control a.active');$($current).removeClass("active");if($($current).next("a").length){$($current).next("a").addClass("active");}else{$('.jcarousel-control a:last').addClass("active");}
$($li).removeClass("active");$($li).eq($('.jcarousel-control a.active').index()).addClass("active");if($('.jcarousel-control a.active').next("a").length==0){$(this).addClass("disabled");}
$("a#mycarousel-prev").removeClass("disabled");if(!$(this).hasClass("disabled")){carousel.next();}
return false;});$('#mycarousel-prev').bind('click',function(){$current=$('.jcarousel-control a.active');if($($current).index()!=0){$($current).removeClass("active");$($current).prev("a").addClass("active");}
$($li).removeClass("active");$($li).eq($('.jcarousel-control a.active').index()).addClass("active");if($('.jcarousel-control a.active').prev("a").length==0){$(this).addClass("disabled");}
$("a#mycarousel-next").removeClass("disabled");if(!$(this).hasClass("disabled")){carousel.prev();}
return false;});}
$("#mycarousel").jcarousel({scroll:1,initCallback:mycarousel_initCallback,buttonNextHTML:null,buttonPrevHTML:null});}
if($(".tabs").length)
$(".tabs").organicTabs({"speed":200});if($(".tooltip-bottom").length){$(".tooltip-bottom").each(function(){$(this).tipTip({maxWidth:"auto"});});}
if($(".tooltip-top").length){$(".tooltip-top").each(function(){$(this).tipTip({maxWidth:"auto",defaultPosition:"top"});});}
if($(".tooltip-left").length){$(".tooltip-left").each(function(){$(this).tipTip({maxWidth:"auto",defaultPosition:"left"});});}
if($(".tooltip-right").length){$(".tooltip-right").each(function(){$(this).tipTip({maxWidth:"auto",defaultPosition:"right"});});}
var $mainNav=$('ul.menu'),optionsList='<option value="" selected>Navigate...</option>';$mainNav.on('mouseenter','li',function(){var $this=$(this),$subMenu=$this.children('ul');if($subMenu.length)$this.addClass('hover');$subMenu.hide().stop(true,true).fadeIn(200);}).on('mouseleave','li',function(){$(this).removeClass('hover').children('ul').stop(true,true).fadeOut(50);});$mainNav.find('li').each(function(){var $this=$(this),$anchor=$this.children('a'),depth=$this.parents('ul').length-1,indent='',text=$anchor.html();text=text.replace(/<span>.*<\/span>/g,'');if(depth){while(depth>0){indent+='--';depth--;}}
var s=($anchor.attr('href')==window.location.href)?"selected = 'selected'":"";optionsList+='<option '+s+' value="'+$anchor.attr('href')+'">'+indent+' '+text+'</option>';}).end().after('<select class="responsive-nav">'+optionsList+'</select>');$('.responsive-nav').on('change',function(){window.location=$(this).val();});$(".social-widget img").hover(function(){$(this).stop().animate({"opacity":"0"},"slow");},function(){$(this).stop().animate({"opacity":"1"},"slow");});});